# Generated by Django 2.0 on 2019-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField()),
                ('product_color', models.CharField(max_length=20)),
            ],
        ),
    ]
